// src/components/resources.tsx
import * as React from 'react'
import { observer } from 'mobx-react'
import aoStore from '../client/store'
import api from '../client/api'
import uuidV1 from 'uuid/v1'

@observer
export default class AoResources extends React.PureComponent<{}> {
  constructor(props) {
    super(props)
    this.renderResources = this.renderResources.bind(this)
  }

  renderResources() {
    const list = aoStore.state.resources.map(r => <li>{r.name}</li>)
    return <ul>{list}</ul>
  }

  createTestResource() {
    api.createResource(uuidV1(), 'test', 0, 'asd', true)
  }

  render() {
    return (
      <React.Fragment>
        <h3>Resource Access</h3>
        <p>
          Connect resources such as door or vending machine using fobtap points
          and raspberry pi running fobtap rfid scan point.
        </p>
        <button type="button" onClick={this.createTestResource}>
          Create Test Resource
        </button>
        {this.renderResources()}
      </React.Fragment>
    )
  }
}

// src/components/Resources.vue
<template lang='pug'>

#resource.container
    .list(v-if='isLoggedIn  && resources.length > 0')
        row(v-for="r in resources", :r="r", :c='panel')
    .padding(v-else)
        h5 dctrl fobtap points
        ol
            li Raspberry pi running fobtap rfid scan point.
            li Door, vending machine, ... many possibilities
            button(@click='createTest') create test resource
</template>

<script>

import Row from "./ResourceRow"
import uuidV1 from 'uuid/v1'

export default {
    computed: {
        resources(){
            return this.$store.state.resources.slice().filter(r => !r.pubkey )
        },
        isLoggedIn(){
            return this.$store.getters.isLoggedIn
        },
        panel(){
            return this.resources.map(r => r.resourceId)
        }
    },
    components:{
        Row,
    },
    methods: {
        createTest(letter){
            let newEv = {
                type: 'resource-created',
                resourceId: uuidV1(),
                name: 'teste',
                charged: 0,
                secret: 'asd',
                trackStock: true
            }
            this.$store.dispatch("makeEvent", newEv)
        },
    }
}

</script>

<style lang='stylus' scoped>

@import '../styles/colours'
@import '../styles/button'
@import '../styles/skeleton'

#resource
    width: 100%

.padding
    padding: 1.987654321em
li
    margin-left: 1em

</style>
